# -*- coding: utf-8 -*-
"""AgroVision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HunpVa5GzdHmLlAS7KC8U_a7mivHrpC_
"""

import gradio as gr
from google import genai
import tempfile
import os

# ==============================
# Gemini API Configuration
# ==============================
client = genai.Client(
    api_key="AIzaSyCmO_WfjskkS1D4PlgkRRDK_k0SbIL5N_w" ## place your API key
)

# ==============================
# Farmer AI System Prompt
# ==============================
FARMER_SYSTEM_PROMPT = """
You are AgroVision AI, a smart agriculture assistant.

Your role:
- Analyze crop, soil, leaf, fruit, and pest images.
- Detect possible plant diseases, nutrient deficiencies, pests, weeds, or crop stress.
- Provide:
   1. Possible disease/problem name
   2. Severity level
   3. Causes
   4. Treatment suggestions
   5. Fertilizer recommendations
   6. Irrigation advice
   7. Prevention methods

Rules:
- Never claim certainty.
- Use simple language for farmers.
- Suggest consulting local agriculture experts for severe damage.
"""

# ==============================
# Menu Prompts
# ==============================
MENU_PROMPTS = {
    "Plant Disease Detection": "Analyze this plant image for diseases.",
    "Soil Analysis": "Analyze soil condition and suggest improvements.",
    "Pest Detection": "Identify possible pests or insect damage.",
    "Fertilizer Suggestions": "Suggest fertilizers based on crop condition.",
    "Crop Health Check": "Analyze overall crop health and stress signs."
}

# ==============================
# Main Function
# ==============================
def farmer_assistant(image, menu_choice, user_prompt):

    try:
        if image is None:
            return "Please upload an image."

        with tempfile.NamedTemporaryFile(suffix=".jpg", delete=False) as temp_file:
            image.save(temp_file.name)
            temp_path = temp_file.name

        uploaded_file = client.files.upload(file=temp_path)

        selected_prompt = MENU_PROMPTS.get(menu_choice, "")

        full_prompt = f"""
        {FARMER_SYSTEM_PROMPT}

        Specialist Mode: {menu_choice}

        Task:
        {selected_prompt}

        Farmer Notes:
        {user_prompt}
        """

        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=[uploaded_file, full_prompt],
        )

        os.remove(temp_path)

        return response.text

    except Exception as e:
        return f"Error: {str(e)}"

# ==============================
# Gradio UI
# ==============================
with gr.Blocks(theme=gr.themes.Soft()) as demo:

    gr.Markdown("# 🌾 AgroVision AI – Smart Farming Assistant")

    with gr.Row():

        with gr.Column(scale=1):

            image_input = gr.Image(type="pil", label="📷 Upload Crop Image")

            menu_dropdown = gr.Dropdown(
                choices=list(MENU_PROMPTS.keys()),
                value="Plant Disease Detection",
                label="🧭 Select Service"
            )

            prompt_input = gr.Textbox(
                label="📝 Additional Details",
                placeholder="Example: Yellow leaves, poor growth...",
                lines=3
            )

            analyze_btn = gr.Button("🔍 Analyze")

        with gr.Column(scale=2):

            output_box = gr.Textbox(
                label="📋 Agriculture AI Report",
                lines=25
            )

    analyze_btn.click(
        fn=farmer_assistant,
        inputs=[image_input, menu_dropdown, prompt_input],
        outputs=output_box
    )

demo.launch(share=True)

