# -*- coding: utf-8 -*-
"""EduVision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pArADXJzi-ff73V3HISxPX9Uo44wWTfF
"""

import gradio as gr
from google import genai
import tempfile
import os

# ==============================
# Gemini API Configuration
# ==============================
client = genai.Client(
    api_key="## place your API key"
)

# ==============================
# Student AI System Prompt
# ==============================
STUDENT_SYSTEM_PROMPT = """
You are EduVision AI, an intelligent student assistant.

Your role:
- Analyze uploaded educational images.
- Help students understand diagrams, handwritten notes, graphs, formulas, and assignments.
- Provide:
   1. Explanation of content
   2. Key concepts
   3. Simple understanding
   4. Important points
   5. Exam tips
   6. Possible questions and answers

Rules:
- Explain in simple student-friendly language.
- Make learning easy and interactive.
"""

# ==============================
# Menu Prompts
# ==============================
MENU_PROMPTS = {
    "Assignment Help": "Analyze assignment image and explain answers.",
    "Handwritten Notes": "Read and explain handwritten notes.",
    "Diagram Explanation": "Explain educational diagram or flowchart.",
    "Math Problem Solver": "Solve and explain math problem step-by-step.",
    "Exam Preparation": "Generate important exam points and summary."
}

# ==============================
# Main Function
# ==============================
def student_assistant(image, menu_choice, user_prompt):

    try:
        if image is None:
            return "Please upload an image."

        with tempfile.NamedTemporaryFile(suffix=".jpg", delete=False) as temp_file:
            image.save(temp_file.name)
            temp_path = temp_file.name

        uploaded_file = client.files.upload(file=temp_path)

        selected_prompt = MENU_PROMPTS.get(menu_choice, "")

        full_prompt = f"""
        {STUDENT_SYSTEM_PROMPT}

        Specialist Mode: {menu_choice}

        Task:
        {selected_prompt}

        Student Request:
        {user_prompt}
        """

        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=[uploaded_file, full_prompt],
        )

        os.remove(temp_path)

        return response.text

    except Exception as e:
        return f"Error: {str(e)}"

# ==============================
# Gradio UI
# ==============================
with gr.Blocks(theme=gr.themes.Soft()) as demo:

    gr.Markdown("# 📚 EduVision AI – Smart Student Assistant")

    with gr.Row():

        with gr.Column(scale=1):

            image_input = gr.Image(type="pil", label="📷 Upload Study Image")

            menu_dropdown = gr.Dropdown(
                choices=list(MENU_PROMPTS.keys()),
                value="Assignment Help",
                label="🧭 Select Mode"
            )

            prompt_input = gr.Textbox(
                label="📝 Additional Request",
                placeholder="Example: Explain in simple words...",
                lines=3
            )

            analyze_btn = gr.Button("🔍 Analyze")

        with gr.Column(scale=2):

            output_box = gr.Textbox(
                label="📋 AI Learning Report",
                lines=25
            )

    analyze_btn.click(
        fn=student_assistant,
        inputs=[image_input, menu_dropdown, prompt_input],
        outputs=output_box
    )

demo.launch(share=True)

