# -*- coding: utf-8 -*-
"""MedVision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AK8Vzjn_o66AWe8jwX6BWF-6bxjGwCma
"""

import gradio as gr
from google import genai
import tempfile
import os

# ==============================
# Gemini API Configuration
# ==============================
client = genai.Client(
    api_key="## place your API key"
)

# ==============================
# Doctor AI System Prompt
# ==============================
DOCTOR_SYSTEM_PROMPT = """
You are MedVision AI, a clinical medical assistant.

Your role:
- Analyze uploaded medical images carefully.
- Assist doctors with preliminary observations.
- Identify possible abnormalities in:
   - X-rays
   - CT scans
   - MRI scans
   - Skin images
   - Reports
   - Lab results

Provide:
   1. Possible findings
   2. Clinical observations
   3. Severity indicators
   4. Differential possibilities
   5. Suggested next diagnostic steps
   6. Emergency warning signs

Rules:
- Never provide final diagnosis.
- Mention limitations clearly.
- Recommend specialist review for critical findings.
- Maintain professional clinical language.
"""

# ==============================
# Menu Prompts
# ==============================
MENU_PROMPTS = {
    "X-Ray Analysis": "Analyze X-ray image for abnormalities.",
    "MRI/CT Scan Review": "Analyze scan image for possible findings.",
    "Lab Report Understanding": "Explain uploaded medical report.",
    "Skin Condition Review": "Analyze dermatological condition.",
    "Clinical Suggestions": "Provide possible next diagnostic recommendations."
}

# ==============================
# Main Function
# ==============================
def doctor_assistant(image, menu_choice, user_prompt):

    try:
        if image is None:
            return "Please upload a medical image."

        with tempfile.NamedTemporaryFile(suffix=".jpg", delete=False) as temp_file:
            image.save(temp_file.name)
            temp_path = temp_file.name

        uploaded_file = client.files.upload(file=temp_path)

        selected_prompt = MENU_PROMPTS.get(menu_choice, "")

        full_prompt = f"""
        {DOCTOR_SYSTEM_PROMPT}

        Specialist Mode: {menu_choice}

        Task:
        {selected_prompt}

        Clinical Notes:
        {user_prompt}
        """

        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=[uploaded_file, full_prompt],
        )

        os.remove(temp_path)

        return response.text

    except Exception as e:
        return f"Error: {str(e)}"

# ==============================
# Gradio UI
# ==============================
with gr.Blocks(theme=gr.themes.Soft()) as demo:

    gr.Markdown("# 🏥 MedVision AI – Clinical Assistant")

    with gr.Row():

        with gr.Column(scale=1):

            image_input = gr.Image(type="pil", label="📷 Upload Medical Image")

            menu_dropdown = gr.Dropdown(
                choices=list(MENU_PROMPTS.keys()),
                value="X-Ray Analysis",
                label="🧭 Select Analysis Mode"
            )

            prompt_input = gr.Textbox(
                label="📝 Clinical Notes",
                placeholder="Example: Persistent cough, chest pain...",
                lines=3
            )

            analyze_btn = gr.Button("🔍 Analyze")

        with gr.Column(scale=2):

            output_box = gr.Textbox(
                label="📋 Medical AI Report",
                lines=28
            )

    analyze_btn.click(
        fn=doctor_assistant,
        inputs=[image_input, menu_dropdown, prompt_input],
        outputs=output_box
    )

demo.launch(share=True)

